{"response": null, "error": "Traceback (most recent call last):\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/jobflow_remote/jobs/run.py\", line 58, in run_remote_job\n    response = job.run(store=store)\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/jobflow/core/job.py\", line 583, in run\n    response = function(*self.function_args, **self.function_kwargs)\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/atomate2/common/jobs/phonons.py\", line 232, in generate_frequencies_eigenvectors\n    return PhononBSDOSDoc.from_forces_born(\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/atomate2/common/schemas/phonons.py\", line 292, in from_forces_born\n    phonon.produce_force_constants(forces=set_of_forces)\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/phonopy/api_phonopy.py\", line 1052, in produce_force_constants\n    self._run_force_constants_from_forces(\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/phonopy/api_phonopy.py\", line 3663, in _run_force_constants_from_forces\n    self._force_constants = get_phonopy_fc2(\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/phonopy/harmonic/force_constants.py\", line 93, in get_fc2\n    atom_list_done = _get_force_constants_disps(\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/phonopy/harmonic/force_constants.py\", line 768, in _get_force_constants_disps\n    solve_force_constants(\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/phonopy/harmonic/force_constants.py\", line 378, in solve_force_constants\n    force_constants[fc_index] = _solve_force_constants_svd(\n  File \"/dss/dsshome1/02/di35jom/miniconda3/envs/jobflow_remote/lib/python3.9/site-packages/phonopy/harmonic/force_constants.py\", line 722, in _solve_force_constants_svd\n    _get_rotated_forces(forces[rot_map_syms[:, i]], site_sym_cart)\nIndexError: too many indices for array: array is 0-dimensional, but 1 were indexed\n", "start_time": {"@module": "datetime", "@class": "datetime", "string": "2024-04-13 21:43:56.590017"}, "end_time": {"@module": "datetime", "@class": "datetime", "string": "2024-04-13 21:44:09.224978"}}